// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTxM_IRa1Cj0tpPJJRFATKRe07XeRl1S8',
    appId: '1:330812523877:web:8823570bf0b9c8e7744d8c',
    messagingSenderId: '330812523877',
    projectId: 'shoutout-55c27',
    authDomain: 'shoutout-55c27.firebaseapp.com',
    storageBucket: 'shoutout-55c27.firebasestorage.app',
    measurementId: 'G-P31H93PFQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT3QnxyGyMgCGC0x_1zKpffj_wl46fMbE',
    appId: '1:330812523877:android:ef3cdf0bcdfaa0b3744d8c',
    messagingSenderId: '330812523877',
    projectId: 'shoutout-55c27',
    storageBucket: 'shoutout-55c27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWnlR8r5RrdcvUnGk8Q2Mh39aP_mijRHE',
    appId: '1:330812523877:ios:a7e09b594f82d0cc744d8c',
    messagingSenderId: '330812523877',
    projectId: 'shoutout-55c27',
    storageBucket: 'shoutout-55c27.firebasestorage.app',
    iosBundleId: 'com.example.shout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWnlR8r5RrdcvUnGk8Q2Mh39aP_mijRHE',
    appId: '1:330812523877:ios:a7e09b594f82d0cc744d8c',
    messagingSenderId: '330812523877',
    projectId: 'shoutout-55c27',
    storageBucket: 'shoutout-55c27.firebasestorage.app',
    iosBundleId: 'com.example.shout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTxM_IRa1Cj0tpPJJRFATKRe07XeRl1S8',
    appId: '1:330812523877:web:4c43058e4448c7e9744d8c',
    messagingSenderId: '330812523877',
    projectId: 'shoutout-55c27',
    authDomain: 'shoutout-55c27.firebaseapp.com',
    storageBucket: 'shoutout-55c27.firebasestorage.app',
    measurementId: 'G-W3Y1WR3636',
  );

}